version: "3.8"

services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations
              python manage.py migrate
              DJANGO_SUPERUSER_USERNAME=teste \
              DJANGO_SUPERUSER_PASSWORD=teste \
              python manage.py createsuperuser \
                      --noinput \
                      --email teste@bycoders.com
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    
    environment:
      - DB_HOST=DB
      - DB_NAME=cnabcoders_db
      - DB_USER=cnabcoders
      - DB_PASS=cn4bc0d3rs

    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=cnabcoders
      - POSTGRES_PASSWORD=cn4bc0d3rs
      - POSTGRES_DB=cnabcoders_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
